#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <gsKit.h>
#include <dmaKit.h>
#include <libpad.h>
#include <string.h>
#include <stdio.h>
#include <libcdvd.h>
#include <libpwroff.h>

#define NEWLIB_PORT_AWARE
#include <fileXio_rpc.h>
#include <iox_stat.h>
#include <io_common.h>

#include "../common/elfloader.h"
#include "app/app_entry.h"
#include "device/device_mgr.h"
#include "gfx/bitmap_font.h"
#include "gfx/icon_cache.h"
#include "config/metadata.h"
#include "theme/theme.h"
#include "ui/dashboard_ui.h"
#include "ui/layout.h"
#include "log/log.h"
#include "audio/audio.h"

/* M10: two embedded themes (colors + an optional background image),
 * deployed onto mc0: at boot the same way target.elf/stage2.elf already
 * are (see the extern block below main() and writeFile() calls) so
 * theme.cfg/background.png are loaded back through the real fileXio
 * path-based loader (theme/theme.c) rather than special-cased in code -
 * proving the same asset-loading pipeline a real, user-supplied theme
 * folder would go through. M15: the loaded Theme[] still drives the
 * Library grid's tile/focus colors and is still cycled from the new
 * System screen (ui/dashboard_ui.c) - only the *background* changed,
 * from a theme's own flat/PNG background to the new animated starfield
 * + floating cubes (ui/background.c), which isn't theme-specific. */
extern unsigned char theme_dark_cfg[];
extern unsigned int size_theme_dark_cfg;
extern unsigned char theme_sunset_cfg[];
extern unsigned int size_theme_sunset_cfg;

#define THEME_COUNT 2
static Theme themes[THEME_COUNT];

/* M11: system services (plan section 9) - disc status/RTC read via
 * libcdvd (cdvdman.irx is already loaded by device_mgr.c's "cdrom0"
 * family refresh, so no extra module load is needed here beyond
 * poweroff.irx itself), plus a real poweroff wired to a pad button. */
static int bcdToDec(u8 bcd)
{
    return ((bcd >> 4) * 10) + (bcd & 0x0F);
}

static const char *diskTypeName(int type)
{
    switch (type) {
    case SCECdNODISC:
        return "no disc";
    case SCECdDETCT:
    case SCECdDETCTCD:
    case SCECdDETCTDVDS:
    case SCECdDETCTDVDD:
        return "detecting";
    case SCECdPSCD:
    case SCECdPSCDDA:
        return "PS1 CD";
    case SCECdPS2CD:
    case SCECdPS2CDDA:
        return "PS2 CD";
    case SCECdPS2DVD:
        return "PS2 DVD";
    case SCECdCDDA:
        return "audio CD";
    case SCECdDVDV:
        return "DVD video";
    case SCECdIllegalMedia:
        return "illegal media";
    default:
        return "unknown";
    }
}

/* Bytes of the built target.elf / stage2.elf, generated by bin2c (see
 * embedded/target_elf.c, embedded/stage2_elf.c) - stage2.elf is always
 * deployed by the dashboard itself (it's the same regardless of which
 * device the actual target lives on); target.elf is only written as a
 * fallback so the browser always has at least one real, launchable
 * entry to demonstrate against on a fresh memory card. */
extern unsigned char target_elf[];
extern unsigned int size_target_elf;
extern unsigned char stage2_elf[];
extern unsigned int size_stage2_elf;

#define MAX_ENTRIES 32

/* Used only if a theme fails to load entirely (missing/corrupt files) -
 * an all-zero Theme would render solid black on black, indistinguishable
 * from a real hang/crash. Matches the M8/M9 hardcoded colors this
 * project shipped before M10, so a theme-load failure degrades to
 * "looks like before", never to "looks broken" (plan section 11). */
static void themeSetFallback(Theme *t)
{
    memset(t, 0, sizeof(*t));
    t->bgColor = GS_SETREG_RGBAQ(0x10, 0x10, 0x14, 0x00, 0x00);
    t->tileColor = GS_SETREG_RGBAQ(0x30, 0x30, 0x38, 0x00, 0x00);
    t->focusColor = GS_SETREG_RGBAQ(0x60, 0x80, 0xC0, 0x00, 0x00);
    t->labelColor = GS_SETREG_RGBAQ(0x80, 0x80, 0x80, 0x80, 0x00);
}

static AppEntry entries[MAX_ENTRIES];
static AppMetadata metas[MAX_ENTRIES];
static int entryCount = 0;

static int hasElfExtension(const char *name)
{
    int len = 0;
    while (name[len])
        len++;
    if (len < 4)
        return 0;
    const char *e = name + len - 4;
    return e[0] == '.' && (e[1] == 'e' || e[1] == 'E') && (e[2] == 'l' || e[2] == 'L') &&
           (e[3] == 'f' || e[3] == 'F');
}

/* stage2.elf is this launcher's own internal chain-load stub (see
 * elfloader.h / stage2/main.c) - it's real, and it does match the .elf
 * filter, but it's not a user-selectable app, and launching it directly
 * (as if it were a target) makes it try to re-launch itself, which
 * produced inconsistent/crashing results during the M8 spike. Excluded
 * by name specifically, rather than never writing it to a real device,
 * since a real device is exactly where it needs to live for chain-
 * loading to work at all. */
static int isInternalPlumbingFile(const char *name)
{
    static const char *target = "stage2.elf";
    int i;
    for (i = 0; target[i]; i++) {
        char c = name[i];
        if (c >= 'A' && c <= 'Z')
            c += 'a' - 'A';
        if (c != target[i])
            return 0;
    }
    return name[i] == '\0';
}

/* Returns a pointer into `path` just past its last ':' or '/' - e.g.
 * "mc0:/target.elf" -> "target.elf". Never allocates; the result aliases
 * the input. */
static const char *baseName(const char *path)
{
    const char *base = path;
    const char *p = path;
    while (*p) {
        if (*p == ':' || *p == '/')
            base = p + 1;
        p++;
    }
    return base;
}

/* Fills entry->title with a sane default derived from its path - the
 * ELF filename, minus its extension (plan section 13's fallback title,
 * used until/unless icon.sys discovery (gfx/icon_cache.c) finds a
 * better one). Never overflows APP_ENTRY_TITLE_MAX. */
static void setDefaultTitle(AppEntry *entry)
{
    const char *base = baseName(entry->path);
    int len = 0;
    while (base[len])
        len++;
    if (len >= 4 && hasElfExtension(base))
        len -= 4;
    if (len > APP_ENTRY_TITLE_MAX - 1)
        len = APP_ENTRY_TITLE_MAX - 1;
    memcpy(entry->title, base, len);
    entry->title[len] = '\0';
}

static DeviceKind deviceKindForFamily(const char *name)
{
    if (strcmp(name, "mc0") == 0)
        return DEVICE_MC0;
    if (strcmp(name, "mc1") == 0)
        return DEVICE_MC1;
    if (strcmp(name, "mass") == 0)
        return DEVICE_MASS;
    if (strcmp(name, "cdrom0") == 0)
        return DEVICE_CDROM;
    if (strcmp(name, "hdd0") == 0)
        return DEVICE_HDD;
    if (strcmp(name, "network") == 0)
        return DEVICE_NETWORK;
    if (strcmp(name, "smb") == 0)
        return DEVICE_SMB;
    return DEVICE_UNKNOWN;
}

/* Scans one device's root directory for .elf/.ELF entries. prefix is
 * expected to already end in '/' (matches every mountPrefix in
 * device_mgr.c), so paths concatenate directly. */
static void scanDevice(const char *prefix, DeviceKind device)
{
    iox_stat_t st;
    if (fileXioGetStat(prefix, &st) < 0)
        return;

    int fd = fileXioDopen(prefix);
    if (fd < 0)
        return;

    iox_dirent_t dirent;
    while (fileXioDread(fd, &dirent) > 0) {
        if (FIO_S_ISDIR(dirent.stat.mode))
            continue;
        if (!hasElfExtension(dirent.name))
            continue;
        if (isInternalPlumbingFile(dirent.name))
            continue;
        if (entryCount >= MAX_ENTRIES)
            break;

        AppEntry *entry = &entries[entryCount];
        char *dst = entry->path;
        const char *p = prefix;
        while (*p)
            *dst++ = *p++;
        const char *n = dirent.name;
        while (*n)
            *dst++ = *n++;
        *dst = '\0';

        entry->device = device;
        entry->iconState = ICON_NOT_REQUESTED;
        entry->iconSlot = -1;
        setDefaultTitle(entry);

        entryCount++;
    }
    fileXioDclose(fd);
}

/* Real PS2 game discs don't have a "*.elf" file anywhere on them - the
 * scan above would never find one - but the actual boot executable they
 * reference IS a genuine ELF binary, just under an arbitrary filename
 * (e.g. "SLUS_123.45"). SYSTEM.CNF at the disc root names it:
 *   BOOT2 = cdrom0:\SLUS_123.45;1
 * elfLoadAndExec() only ever validated ELF magic, never the filename, so
 * once this path is known it launches exactly like any other entry - no
 * new loader logic needed, only a different way to discover the path.
 * PS1 discs use "BOOT" (no "2") and a completely different, non-ELF
 * executable format requiring PS1 BIOS compatibility mode on real
 * hardware - out of scope, and this function's "BOOT2"-only match
 * naturally skips them rather than finding a path we couldn't load
 * anyway. Returns 0 and fills out (converting backslashes to forward
 * slashes; the ";N" ISO9660 version suffix is kept as-is since cdrom0:
 * needs it to resolve the file) on success. */
/* fileXioOpen()/fileXioDopen()+fileXioDread() against cdrom0: turned out
 * unreliable in practice - fileXioGetStat() on the root succeeds (that's
 * how device_mgr.c's probeFs() sees the family as available at all), but
 * both a direct SYSTEM.CNF open and a root directory listing failed
 * outright, confirmed via live PCSX2 memory reads. cdvdfsv's fileXio
 * compatibility layer apparently doesn't fully cover file lookup/listing
 * the way it does for MC/USB's FAT-style drivers. libcdvd's own,
 * CD-specific file API - sceCdSearchFile() + sceCdRead() - is what
 * wLaunchELF/OPL actually use for this, and doesn't go through
 * fileXio/iomanX at all. Confirmed working end-to-end against a real
 * PS2 disc (SYSTEM.CNF found, read, and parsed to a real boot path). */
static int parseDiscBootPath(char *out, int outSize)
{
    sceCdlFILE file;
    if (!sceCdSearchFile(&file, "\\SYSTEM.CNF;1"))
        return -1;

    unsigned int sectors = (file.size + 2047) / 2048;
    if (sectors == 0)
        sectors = 1;
    if (sectors > 4) /* SYSTEM.CNF is always a handful of lines - guard against a bogus size */
        sectors = 4;

    static unsigned char cdBuf[4 * 2048] __attribute__((aligned(64)));
    static sceCdRMode mode;
    mode.trycount = 0;
    mode.spindlctrl = 0;
    mode.datapattern = SCECdSecS2048;
    mode.pad = 0;

    if (!sceCdRead(file.lsn, sectors, cdBuf, &mode))
        return -1;
    sceCdSync(0); /* sceCdRead is non-blocking - this is the documented way to wait for it */

    unsigned int n = file.size;
    if (n >= sizeof(cdBuf))
        n = sizeof(cdBuf) - 1;
    cdBuf[n] = '\0';

    char *line = strtok((char *)cdBuf, "\r\n");
    while (line) {
        if (strncmp(line, "BOOT2", 5) == 0) {
            char *eq = strchr(line, '=');
            if (!eq)
                return -1;
            char *p = eq + 1;
            while (*p == ' ')
                p++;
            int i = 0;
            while (*p && *p != ' ' && *p != '\t' && i < outSize - 1) {
                out[i++] = (*p == '\\') ? '/' : *p;
                p++;
            }
            out[i] = '\0';
            return (i > 0) ? 0 : -1;
        }
        line = strtok(NULL, "\r\n");
    }
    return -1;
}

static int writeFile(const char *path, const void *data, unsigned int size)
{
    int fd = fileXioOpen(path, FIO_O_WRONLY | FIO_O_CREAT | FIO_O_TRUNC, 0666);
    if (fd < 0)
        return fd;
    int written = fileXioWrite(fd, data, size);
    fileXioClose(fd);
    return (written == (int)size) ? 0 : -1;
}

/* fileXioMkdir fails (harmlessly) if the directory already exists - not
 * checked, since either way the writeFile() calls right after this are
 * what actually determine success. */
static void ensureDir(const char *path)
{
    fileXioMkdir(path, 0777);
}

/* M13 (plan section 11, "removed storage mid-browse"): rebuilds entries[]
 * from scratch against the families' *current* available state - shared
 * by the boot-time scan and the periodic mid-session rescan below, so a
 * device pulled or reinserted after boot is actually reflected in the
 * browsable grid, not just safely failing if launched (which was already
 * true before this, just not proactive). Assumes stage2.elf/target.elf
 * are already on mc0: (main() writes them before ever calling this) -
 * the entryCount==0 fallback path below depends on target.elf actually
 * existing by this point.
 *
 * M15: every (re)populated entry starts with iconState ==
 * ICON_NOT_REQUESTED - a full rescan can reuse the same entries[] slot
 * for a completely different app (or the same one), and the icon cache
 * (gfx/icon_cache.c) only ever trusts an entry's own iconState/iconSlot
 * fields, never assumes anything about what previously lived at that
 * array index, so this is always safe: a stale LOADED flag left over
 * from before this rescan would otherwise show a wrong, unrelated
 * cached icon. */
static void rescanEntries(DeviceFamily *families, int familyCount)
{
    entryCount = 0;

    int i;
    for (i = 0; i < familyCount; i++) {
        if (families[i].mountPrefix && families[i].available)
            scanDevice(families[i].mountPrefix, deviceKindForFamily(families[i].name));
    }

    /* A real game disc, if one's mounted, needs its own discovery path
     * (see parseDiscBootPath()'s header comment) rather than the
     * extension-based scan above, which will never find anything on
     * commercial disc media. */
    for (i = 0; i < familyCount; i++) {
        if (strcmp(families[i].name, "cdrom0") == 0 && families[i].available) {
            if (entryCount < MAX_ENTRIES && parseDiscBootPath(entries[entryCount].path, sizeof(entries[0].path)) == 0) {
                AppEntry *entry = &entries[entryCount];
                entry->device = DEVICE_CDROM;
                entry->iconState = ICON_NOT_REQUESTED;
                entry->iconSlot = -1;
                setDefaultTitle(entry);
                entryCount++;
            }
            break;
        }
    }

    /* Fallback so the browser always has something to show and launch
     * on a fresh memory card with no homebrew on it yet. */
    if (entryCount == 0) {
        const char *fallback = "mc0:/target.elf";
        AppEntry *entry = &entries[0];
        char *dst = entry->path;
        while (*fallback)
            *dst++ = *fallback++;
        *dst = '\0';
        entry->device = DEVICE_MC0;
        entry->iconState = ICON_NOT_REQUESTED;
        entry->iconSlot = -1;
        setDefaultTitle(entry);
        entryCount = 1;
    }

    /* M9: per-app metadata (launch count, favorite, M15's launch order) -
     * one small sibling .cfg file per entry (config/metadata.c). Missing
     * or corrupt files both degrade to all-zero defaults, so this never
     * blocks the scan. */
    for (i = 0; i < entryCount; i++)
        metadataLoad(entries[i].path, &metas[i]);
}

int main(int argc, char *argv[])
{
    SifInitRpc(0);

    SifLoadModule("rom0:SIO2MAN", 0, NULL);
    SifLoadModule("rom0:PADMAN", 0, NULL);
    SifLoadModule("host:modules/iomanX.irx", 0, NULL);
    SifLoadModule("host:modules/fileXio.irx", 0, NULL);
    fileXioInit();
    fileXioSetRWBufferSize(128 * 1024);

    logInit();
    logMsg("boot: dashboard starting");

    /* M11: poweroff is its own always-loaded system service, not tied to
     * a device family - unlike cdvdman.irx (loaded lazily by the
     * "cdrom0" device_mgr.c family below), a poweroff button should work
     * regardless of which devices are actually present. */
    SifLoadModule("host:modules/poweroff.irx", 0, NULL);
    poweroffInit();

    /* M14: optional sound - a failure anywhere in here (module load,
     * audsrv_init, format config) just leaves audioPlayBlip() a silent
     * no-op for the rest of the session, never something that blocks or
     * degrades the rest of the dashboard boot. */
    audioInit();
    audioPlayMusic();

    /* Device manager: lazily load + probe every family once at boot (M6's
     * scoping note still applies - only-load-on-navigation belongs to a
     * later UI-driven refresh, once there's more than one screen to
     * navigate between). */
    int familyCount;
    DeviceFamily *families = deviceMgrGetFamilies(&familyCount);
    int i;
    for (i = 0; i < familyCount; i++)
        deviceMgrRefresh(&families[i]);

    /* stage2 is deployed unconditionally - every launch chains through it
     * regardless of which device the target itself lives on. Likewise,
     * always refresh target.elf's on-disk bytes to match this build:
     * this is this project's own trivial test stub (not a real user's
     * homebrew), so keeping it in sync every boot is the right call for
     * testing, even though a real dashboard should never silently
     * overwrite a user's actual app files. Refreshing the bytes is kept
     * separate from registering it as a browsable entry - rescanEntries()
     * below finds it as a normal scanned entry once it's actually there. */
    writeFile("mc0:/stage2.elf", stage2_elf, size_stage2_elf);
    writeFile("mc0:/target.elf", target_elf, size_target_elf);

    /* M10: deploy both embedded themes onto mc0: every boot too, exactly
     * like stage2/target above - keeps this project's own bundled themes
     * in sync with the build, and gives theme/theme.c a real on-disk
     * folder to load through fileXio rather than special-casing embedded
     * data in the loader itself.
     *
     * One directory level under root, not nested under a "themes/"
     * parent: the PS2 memory card filesystem only supports one level of
     * subdirectory below root at all (every real save folder - e.g.
     * "BASCUS-90123" - lives directly in MC root; mcman has no concept
     * of a folder-of-folders). A "mc0:/themes/dark/" layout is two
     * levels deep and silently fails to be created on MC. */
    ensureDir("mc0:/theme_dark");
    ensureDir("mc0:/theme_sunset");
    writeFile("mc0:/theme_dark/theme.cfg", theme_dark_cfg, size_theme_dark_cfg);
    writeFile("mc0:/theme_sunset/theme.cfg", theme_sunset_cfg, size_theme_sunset_cfg);

    rescanEntries(families, familyCount);

    /* gsKit_init_global() auto-detects Mode/Interlace/Field/Width/Height -
     * confirmed working as-is since M1/M2, don't override. */
    GSGLOBAL *gsGlobal = gsKit_init_global();
    gsGlobal->PrimAlphaEnable = GS_SETTING_ON;

    dmaKit_init(D_CTRL_RELE_OFF, D_CTRL_MFD_OFF, D_CTRL_STS_UNSPEC,
                D_CTRL_STD_OFF, D_CTRL_RCYC_8, 1 << DMA_CHANNEL_GIF);
    dmaKit_chan_init(DMA_CHANNEL_GIF);

    gsKit_init_screen(gsGlobal);
    gsKit_mode_switch(gsGlobal, GS_ONESHOT);

    /* M13: bitmapFontInit() can fail (VRAM exhaustion, allocation
     * failure) - previously discarded entirely, so a failure here would
     * have left every later bitmapFontPrint() call drawing through an
     * uninitialized/zeroed BitmapFont (a texture with Vram=0, aliasing
     * the framebuffer). fontOk gates every text draw below so a failure
     * degrades to a text-free but otherwise fully functional UI (tiles,
     * launching, navigation all still work) instead of corrupting the
     * framebuffer. */
    BitmapFont font;
    int fontOk = (bitmapFontInit(&font, gsGlobal) == 0);
    if (!fontOk)
        logMsg("font init failed, running text-free");

    /* M10: load both bundled themes once at boot (not per-switch) - a
     * theme's background texture, if any, is decoded and uploaded to
     * VRAM exactly once and simply referenced thereafter, so cycling
     * between themes at runtime never re-allocates VRAM (gsKit's
     * allocator has no free(), so repeated alloc-on-switch would
     * eventually exhaust the 4MB budget measured in M7). If a theme
     * fails to load (missing/corrupt files), it keeps a safe all-zero
     * struct - drawing with black tiles/labels rather than crashing. */
    if (themeLoad("mc0:/theme_dark/", &themes[0], gsGlobal) < 0) {
        themeSetFallback(&themes[0]);
        logMsg("theme load failed: dark, using fallback colors");
    }
    if (themeLoad("mc0:/theme_sunset/", &themes[1], gsGlobal) < 0) {
        themeSetFallback(&themes[1]);
        logMsg("theme load failed: sunset, using fallback colors");
    }

    /* M15: the icon subsystem (gfx/icon_cache.c) - a small, fixed-size
     * VRAM atlas (fallback badges + a bounded LRU pool of real decoded
     * PS2 app icons). Same allocate-once-at-boot discipline as the font/
     * theme textures above; a failure here (VRAM exhaustion) degrades to
     * "no icons at all" rather than crashing - see icon_cache.h's
     * `ready` field and every draw call gating on it. */
    IconCache iconCache;
    if (iconCacheInit(&iconCache, gsGlobal) < 0)
        logMsg("icon cache init failed, running without app icons");

    DashboardUi ui;
    dashboardUiInit(&ui, THEME_COUNT);

    static char padBuf[256] __attribute__((aligned(64)));
    padInit(0);
    padPortOpen(0, 0, padBuf);

    /* Title-safe layout (plan section 4) - computed once (the runtime
     * resolution doesn't change), shared by main.c's own status-line/
     * debug-overlay drawing below and by dashboard_ui.c's per-screen
     * content (ui/layout.c ensures both use the exact same numbers). */
    LayoutRect rect;
    layoutComputeSafeArea(&rect, gsGlobal, LAYOUT_STATUS_LINE_HEIGHT);

    u32 prevPressed = 0;

    /* M13 (plan section 11's own explicit task, "logging/debug overlay") -
     * START was unused (SELECT is poweroff, TRIANGLE is favorite, CROSS
     * launches/confirms, D-pad navigates). */
    int overlayVisible = 0;
    int debugLoggingOn = 0; /* mc0:/launcher.log disk flush - off by default, toggled with SQUARE on the overlay */

    /* M11: disc status/RTC are polled roughly once a second, not every
     * frame - both go over SIF RPC to the IOP, and a status line that's
     * a second stale is unnoticeable while sixty extra RPC round-trips a
     * second for no visible benefit isn't free (plan section 10). ~60
     * frames is an approximation (NTSC is actually 59.94, PAL is 50) -
     * fine for a once-a-second cosmetic refresh. */
    int statusFrameCounter = 0;
    static char statusLine[64] __attribute__((aligned(64)));
    statusLine[0] = '\0';

    /* M13 (plan section 11): both of these were previously silent - a
     * failed launch (bad ELF, or its device removed since the boot-time
     * scan) or a disconnected controller left the UI looking frozen,
     * indistinguishable from an actual hang. Both reuse the status
     * line's existing render slot rather than adding a new one -
     * disconnect takes priority over a launch-failure message, since
     * it's the more pressing state and also because a disconnected pad
     * can't be the one that just triggered a launch attempt anyway. */
    char overrideMsg[64];
    int launchFailedFramesLeft = 0;
    int disconnectFrames = 0;

    /* M13 (plan section 11, "removed storage mid-browse"): a lightweight
     * recheck of removable-media families every ~3 seconds (180 frames) -
     * long enough to be cheap (this is a real IOP RPC per family, not
     * free), short enough that pulling a USB stick or swapping a disc
     * gets reflected in the browsable grid without needing to wait long
     * or trigger it by trying to launch something. Only families with a
     * quickProbe are ever rechecked - see device_mgr.h. */
    int rescanFrameCounter = 0;

    /* M15 follow-up: -1 is a sentinel distinct from every real
     * sceCdGetDiskType() return value (SCECdNODISC is 0x00, every other
     * type is a positive enum value) - guarantees the disc-sync check
     * below runs at least once on the very first status poll, syncing
     * entries[] against whatever disc is already in the drive at boot. */
    int lastDiskType = -1;

    /* M15: a monotonic "launch order" counter - see config/metadata.h's
     * lastLaunchOrder field. Persists for the process's whole lifetime,
     * same as every other loop-persistent variable here. */
    unsigned int launchOrderCounter = 0;

    while (1) {
        audioTick();

        if (rescanFrameCounter == 0) {
            int changed = 0;
            for (i = 0; i < familyCount; i++) {
                int wasAvailable = families[i].available;
                deviceMgrQuickRescan(&families[i]);
                if (families[i].available != wasAvailable)
                    changed = 1;
            }
            if (changed)
                rescanEntries(families, familyCount);
        }
        rescanFrameCounter = (rescanFrameCounter + 1) % 180;

        if (statusFrameCounter == 0) {
            /* sceCdReadClock() fills this via a SIF RPC - the IOP DMAs
             * its response back into EE memory. An unaligned/unpadded
             * stack struct here lets that DMA touch a whole 64-byte
             * cache line, which can silently clobber whatever *other*
             * stack variables happen to share it - not just this 8-byte
             * struct. Exactly the padBuf/SIO2 gotcha above, applied to a
             * different IOP driver: static+aligned gives it a dedicated
             * cache line the compiler won't pack anything else into
             * (confirmed real: this was corrupting statusLine's own text
             * once a second, right when this RPC ran). */
            static sceCdCLOCK clock __attribute__((aligned(64)));
            int diskType = sceCdGetDiskType();

            /* M15 follow-up: detects a disc swap and re-syncs entries[]
             * against it. This is driven by sceCdGetDiskType()'s own
             * transitions (the authoritative libcdvd-level signal), not
             * cdrom0's fileXioGetStat()-based `available` flag (M13's
             * periodic device recheck) - a disc swap doesn't necessarily
             * flip that flag at all, since cdvdfsv can keep reporting
             * cdrom0:/ as present the whole time. Critically, this also
             * waits on sceCdDiskReady() before trusting sceCdSearchFile/
             * sceCdRead again (parseDiscBootPath, above) - without that
             * handshake, those calls can return stale data cached from
             * the *previous* disc rather than failing outright, which is
             * exactly what was happening here: the swap was detected but
             * SYSTEM.CNF kept reading back as the old disc's. */
            if (diskType != lastDiskType) {
                lastDiskType = diskType;

                int isRealDisc = (diskType != SCECdNODISC && diskType != SCECdDETCT && diskType != SCECdDETCTCD &&
                                   diskType != SCECdDETCTDVDS && diskType != SCECdDETCTDVDD);

                int discIndex = -1;
                {
                    int j;
                    for (j = 0; j < entryCount; j++) {
                        if (entries[j].device == DEVICE_CDROM) {
                            discIndex = j;
                            break;
                        }
                    }
                }

                int changed = 0;
                if (isRealDisc) {
                    /* Bounded retry, not an indefinite block - matches
                     * every other "wait for hardware" retry loop in this
                     * codebase (device_mgr.c's probeUSB/probeNetwork).
                     * sceCdDiskReady(1) is the non-blocking "check status
                     * and return immediately" mode (mode 0 would block
                     * the whole render loop until ready). */
                    int ready = 0;
                    int attempt;
                    for (attempt = 0; attempt < 100 && !ready; attempt++) {
                        if (sceCdDiskReady(1) == SCECdComplete)
                            ready = 1;
                    }

                    if (ready) {
                        char newDiscPath[APP_ENTRY_PATH_MAX];
                        int found = (parseDiscBootPath(newDiscPath, sizeof(newDiscPath)) == 0);
                        if (found && (discIndex < 0 || strcmp(entries[discIndex].path, newDiscPath) != 0))
                            changed = 1;
                        else if (!found && discIndex >= 0)
                            changed = 1;
                    }
                } else if (discIndex >= 0) {
                    changed = 1; /* disc removed - drop the stale entry */
                }

                if (changed)
                    rescanEntries(families, familyCount);
            }

            if (sceCdReadClock(&clock)) {
                sprintf(statusLine, "%s | 20%02d-%02d-%02d %02d:%02d:%02d", diskTypeName(diskType),
                        bcdToDec(clock.year), bcdToDec(clock.month), bcdToDec(clock.day), bcdToDec(clock.hour),
                        bcdToDec(clock.minute), bcdToDec(clock.second));
            } else {
                sprintf(statusLine, "%s | RTC unavailable", diskTypeName(diskType));
            }
        }
        statusFrameCounter = (statusFrameCounter + 1) % 60;

        u32 pressed = 0;
        if (padGetState(0, 0) == PAD_STATE_STABLE) {
            struct padButtonStatus buttons;
            padRead(0, 0, &buttons);
            pressed = 0xffff ^ buttons.btns;
            if (disconnectFrames > 30)
                logMsg("controller reconnected");
            disconnectFrames = 0;
        } else {
            /* A handful of not-stable frames is normal (between reads,
             * brief bus contention) - only treat it as a real disconnect
             * once it's sustained for about half a second, so momentary
             * blips don't flash the message or spam the log. */
            if (disconnectFrames == 30)
                logMsg("controller disconnected");
            if (disconnectFrames < 1000000)
                disconnectFrames++;
        }
        u32 edge = pressed & ~prevPressed;
        prevPressed = pressed;

        if (edge & PAD_START)
            overlayVisible = !overlayVisible;

        /* SQUARE explicitly toggles the mc0:/launcher.log disk flush
         * on/off (see log.c) - only live while the overlay is showing,
         * so it can't be toggled by accident during normal navigation.
         * Deliberately separate from just viewing the overlay: opening
         * it to glance at recent events shouldn't itself start writing
         * to MC on every device probe/launch, per the user's own call
         * that those are two different decisions. */
        if (overlayVisible && (edge & PAD_SQUARE)) {
            debugLoggingOn = !debugLoggingOn;
            logSetDebugEnabled(debugLoggingOn);
        }

        /* M11: SELECT is a real, immediate system poweroff - not
         * expected to "return" to the loop on hardware, but PCSX2's own
         * behavior when a homebrew ELF calls this is untested territory
         * for this project, so no assumption is made about what happens
         * next. Kept as a global shortcut alongside the new System >
         * Power row (ui/dashboard_ui.c) - both call the same
         * poweroffShutdown(), neither disables the other. */
        if (edge & PAD_SELECT)
            poweroffShutdown();

        /* M15: screen navigation/selection - dashboard_ui.c owns Home/
         * Library/System's own focus state and reports back at most one
         * action; the actual launch/favorite/poweroff side effects stay
         * here, unchanged from before, so the existing, already-tested
         * code paths (elfLoadAndExec's chain-load, metadataSave's CRC-
         * trailer write) are untouched (plan section 14). */
        UiAction action = dashboardUiHandleInput(&ui, edge, entries, metas, entryCount, families, familyCount);

        if (action.kind == UI_ACTION_TOGGLE_FAVORITE && action.entryIndex >= 0 && action.entryIndex < entryCount) {
            metas[action.entryIndex].favorite = !metas[action.entryIndex].favorite;
            metadataSave(entries[action.entryIndex].path, &metas[action.entryIndex]);
        } else if (action.kind == UI_ACTION_LAUNCH && action.entryIndex >= 0 && action.entryIndex < entryCount) {
            /* Persist the launch before handing off, not after - a
             * successful launch never returns here to record it. */
            metas[action.entryIndex].launchCount++;
            metas[action.entryIndex].lastLaunchOrder = ++launchOrderCounter;
            metadataSave(entries[action.entryIndex].path, &metas[action.entryIndex]);

            logMsg("launching: %s", entries[action.entryIndex].path);

            char *stage2Argv[2];
            stage2Argv[0] = entries[action.entryIndex].path;
            stage2Argv[1] = "0"; /* reset_iop: false, the common case */
            elfLoadAndExec("mc0:/stage2.elf", 0, 2, stage2Argv);
            /* Not expected to return - if it does, the launch failed;
             * fall through and keep the browser up rather than hanging
             * (plan section 11's fallback philosophy). */
            logMsg("launch failed: %s", entries[action.entryIndex].path);
            launchFailedFramesLeft = 180;
        } else if (action.kind == UI_ACTION_POWEROFF) {
            poweroffShutdown();
        }

        /* Priority: disconnected controller > a recent launch failure >
         * the normal disc/RTC readout. Both overrides count down/reset
         * on their own regardless of whether text actually gets drawn
         * this frame, so they behave correctly even if fontOk is false.
         * Computed before dashboardUiDraw() since the System screen's
         * own "Disc" row also shows this same line (ui/dashboard_ui.c). */
        const char *lineToShow = statusLine;
        if (disconnectFrames > 30) {
            strcpy(overrideMsg, "controller disconnected");
            lineToShow = overrideMsg;
        } else if (launchFailedFramesLeft > 0) {
            strcpy(overrideMsg, "launch failed");
            lineToShow = overrideMsg;
            launchFailedFramesLeft--;
        }

        /* M15: the animated PSBBN-style background plus whichever of
         * Home/Library/System is current - replaces the old flat-color/
         * theme-background clear and 4-column grid entirely (see
         * ui/dashboard_ui.c and ui/background.c). */
        dashboardUiDraw(&ui, gsGlobal, &font, fontOk, themes, entries, metas, entryCount, families, familyCount,
                         &iconCache, lineToShow);

        /* Persistent status-line strip, below the title-safe content
         * area dashboard_ui.c just drew into - main.c's own since it
         * spans every screen identically and isn't part of any one
         * screen's content (plan section 4's reserved bottom row). */
        layoutFillOpaque(gsGlobal, 0.0f, rect.safeBottom, rect.screenW, rect.screenH, 0, themes[ui.currentTheme].bgColor);
        if (fontOk)
            bitmapFontPrint(gsGlobal, &font, rect.marginX, rect.safeBottom + 2.0f, themes[ui.currentTheme].labelColor,
                             lineToShow);

        /* M13 debug overlay (toggled with START) - a plain, opaque dark
         * panel over the whole safe area, showing the most recent log
         * lines newest-at-bottom. Deliberately opaque rather than
         * translucent - alpha blending has been the single most
         * troublesome GS state in this whole project (M7's blend
         * equation, M11's Z-test discovery); a solid panel is simplest
         * and needs none of that. */
        if (overlayVisible) {
            layoutFillOpaque(gsGlobal, rect.marginX, rect.marginY, rect.marginX + rect.safeW, rect.safeBottom, 1,
                              GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x00, 0x00));

            if (fontOk) {
                char header[48];
                sprintf(header, "[SQUARE] disk logging: %s", debugLoggingOn ? "ON" : "OFF");
                bitmapFontPrint(gsGlobal, &font, rect.marginX + 4.0f, rect.marginY + 4.0f,
                                GS_SETREG_RGBAQ(0xFF, 0xE0, 0x80, 0x80, 0x00), header);

                int n = logLineCount();
                int maxRows = (int)((rect.safeBottom - rect.marginY) / 16.0f) - 2;
                int startIdx = (n > maxRows) ? n - maxRows : 0;
                int row = 0;
                while (startIdx + row < n) {
                    const char *line = logLine(startIdx + row);
                    if (line)
                        bitmapFontPrint(gsGlobal, &font, rect.marginX + 4.0f, rect.marginY + 4.0f + (row + 1) * 16.0f,
                                         GS_SETREG_RGBAQ(0xFF, 0xFF, 0xFF, 0x80, 0x00), line);
                    row++;
                }
            }
        }

        gsKit_queue_exec(gsGlobal);
        gsKit_sync_flip(gsGlobal);
    }

    return 0;
}
