#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <gsKit.h>
#include <dmaKit.h>
#include <libpad.h>
#include <string.h>
#include <stdio.h>
#include <libcdvd.h>
#include <libpwroff.h>

#define NEWLIB_PORT_AWARE
#include <fileXio_rpc.h>
#include <iox_stat.h>
#include <io_common.h>

#include "../common/elfloader.h"
#include "device/device_mgr.h"
#include "gfx/bitmap_font.h"
#include "config/metadata.h"
#include "theme/theme.h"

/* M10: two embedded themes (colors + an optional background image),
 * deployed onto mc0: at boot the same way target.elf/stage2.elf already
 * are (see the extern block below main() and writeFile() calls) so
 * theme.cfg/background.png are loaded back through the real fileXio
 * path-based loader (theme/theme.c) rather than special-cased in code -
 * proving the same asset-loading pipeline a real, user-supplied theme
 * folder would go through. */
extern unsigned char theme_dark_cfg[];
extern unsigned int size_theme_dark_cfg;
extern unsigned char theme_sunset_cfg[];
extern unsigned int size_theme_sunset_cfg;

#define THEME_COUNT 2
static Theme themes[THEME_COUNT];
static int currentTheme = 0;

/* M11: system services (plan section 9) - disc status/RTC read via
 * libcdvd (cdvdman.irx is already loaded by device_mgr.c's "cdrom0"
 * family refresh, so no extra module load is needed here beyond
 * poweroff.irx itself), plus a real poweroff wired to a pad button. */
static int bcdToDec(u8 bcd)
{
    return ((bcd >> 4) * 10) + (bcd & 0x0F);
}

static const char *diskTypeName(int type)
{
    switch (type) {
    case SCECdNODISC:
        return "no disc";
    case SCECdDETCT:
    case SCECdDETCTCD:
    case SCECdDETCTDVDS:
    case SCECdDETCTDVDD:
        return "detecting";
    case SCECdPSCD:
    case SCECdPSCDDA:
        return "PS1 CD";
    case SCECdPS2CD:
    case SCECdPS2CDDA:
        return "PS2 CD";
    case SCECdPS2DVD:
        return "PS2 DVD";
    case SCECdCDDA:
        return "audio CD";
    case SCECdDVDV:
        return "DVD video";
    case SCECdIllegalMedia:
        return "illegal media";
    default:
        return "unknown";
    }
}

/* Bytes of the built target.elf / stage2.elf, generated by bin2c (see
 * embedded/target_elf.c, embedded/stage2_elf.c) - stage2.elf is always
 * deployed by the dashboard itself (it's the same regardless of which
 * device the actual target lives on); target.elf is only written as a
 * fallback so the browser always has at least one real, launchable
 * entry to demonstrate against on a fresh memory card. */
extern unsigned char target_elf[];
extern unsigned int size_target_elf;
extern unsigned char stage2_elf[];
extern unsigned int size_stage2_elf;

/* M8 note: this is the first milestone with a real, navigable dashboard
 * UI - a grid of launchable ELF entries scanned across every available
 * device family (M6), rendered with gsKit (M1/M2/M7's proven patterns),
 * driven by the pad (M1/M2). Text labels were a deliberate, documented
 * gap in M8 (gsKit's own font system loads glyph sheets by path, hitting
 * the same POSIX/fopen device-table gap confirmed in M4/M7) - closed at
 * the start of M9 using wLaunchELF's bitmap font data (gfx/font_uLE.c,
 * gfx/bitmap_font.c), decoded directly into a GS texture atlas the same
 * way M7's icon atlas works, sidestepping gsKit's path-based loader
 * entirely rather than fighting the same fileXio-vs-fopen issue again. */

#define GRID_COLS 4
#define MAX_ENTRIES 32
#define TITLE_SAFE_MARGIN 0.08f

typedef struct {
    char path[256];
} AppEntry;

/* Used only if a theme fails to load entirely (missing/corrupt files) -
 * an all-zero Theme would render solid black on black, indistinguishable
 * from a real hang/crash. Matches the M8/M9 hardcoded colors this
 * project shipped before M10, so a theme-load failure degrades to
 * "looks like before", never to "looks broken" (plan section 11). */
static void themeSetFallback(Theme *t)
{
    memset(t, 0, sizeof(*t));
    t->bgColor = GS_SETREG_RGBAQ(0x10, 0x10, 0x14, 0x00, 0x00);
    t->tileColor = GS_SETREG_RGBAQ(0x30, 0x30, 0x38, 0x00, 0x00);
    t->focusColor = GS_SETREG_RGBAQ(0x60, 0x80, 0xC0, 0x00, 0x00);
    t->labelColor = GS_SETREG_RGBAQ(0x80, 0x80, 0x80, 0x80, 0x00);
}

static AppEntry entries[MAX_ENTRIES];
static AppMetadata metas[MAX_ENTRIES];
static int entryCount = 0;

static int hasElfExtension(const char *name)
{
    int len = 0;
    while (name[len])
        len++;
    if (len < 4)
        return 0;
    const char *e = name + len - 4;
    return e[0] == '.' && (e[1] == 'e' || e[1] == 'E') && (e[2] == 'l' || e[2] == 'L') &&
           (e[3] == 'f' || e[3] == 'F');
}

/* stage2.elf is this launcher's own internal chain-load stub (see
 * elfloader.h / stage2/main.c) - it's real, and it does match the .elf
 * filter, but it's not a user-selectable app, and launching it directly
 * (as if it were a target) makes it try to re-launch itself, which
 * produced inconsistent/crashing results during the M8 spike. Excluded
 * by name specifically, rather than never writing it to a real device,
 * since a real device is exactly where it needs to live for chain-
 * loading to work at all. */
static int isInternalPlumbingFile(const char *name)
{
    static const char *target = "stage2.elf";
    int i;
    for (i = 0; target[i]; i++) {
        char c = name[i];
        if (c >= 'A' && c <= 'Z')
            c += 'a' - 'A';
        if (c != target[i])
            return 0;
    }
    return name[i] == '\0';
}

/* Scans one device's root directory for .elf/.ELF entries. prefix is
 * expected to already end in '/' (matches every mountPrefix in
 * device_mgr.c), so paths concatenate directly. */
static void scanDevice(const char *prefix)
{
    iox_stat_t st;
    if (fileXioGetStat(prefix, &st) < 0)
        return;

    int fd = fileXioDopen(prefix);
    if (fd < 0)
        return;

    iox_dirent_t dirent;
    while (fileXioDread(fd, &dirent) > 0) {
        if (FIO_S_ISDIR(dirent.stat.mode))
            continue;
        if (!hasElfExtension(dirent.name))
            continue;
        if (isInternalPlumbingFile(dirent.name))
            continue;
        if (entryCount >= MAX_ENTRIES)
            break;

        char *dst = entries[entryCount].path;
        const char *p = prefix;
        while (*p)
            *dst++ = *p++;
        const char *n = dirent.name;
        while (*n)
            *dst++ = *n++;
        *dst = '\0';
        entryCount++;
    }
    fileXioDclose(fd);
}

/* Returns a pointer into `path` just past its last ':' or '/' - e.g.
 * "mc0:/target.elf" -> "target.elf". Never allocates; the result aliases
 * the input. */
static const char *baseName(const char *path)
{
    const char *base = path;
    const char *p = path;
    while (*p) {
        if (*p == ':' || *p == '/')
            base = p + 1;
        p++;
    }
    return base;
}

static int writeFile(const char *path, const void *data, unsigned int size)
{
    int fd = fileXioOpen(path, FIO_O_WRONLY | FIO_O_CREAT | FIO_O_TRUNC, 0666);
    if (fd < 0)
        return fd;
    int written = fileXioWrite(fd, data, size);
    fileXioClose(fd);
    return (written == (int)size) ? 0 : -1;
}

/* fileXioMkdir fails (harmlessly) if the directory already exists - not
 * checked, since either way the writeFile() calls right after this are
 * what actually determine success. */
static void ensureDir(const char *path)
{
    fileXioMkdir(path, 0777);
}

int main(int argc, char *argv[])
{
    SifInitRpc(0);

    SifLoadModule("rom0:SIO2MAN", 0, NULL);
    SifLoadModule("rom0:PADMAN", 0, NULL);
    SifLoadModule("host:modules/iomanX.irx", 0, NULL);
    SifLoadModule("host:modules/fileXio.irx", 0, NULL);
    fileXioInit();
    fileXioSetRWBufferSize(128 * 1024);

    /* M11: poweroff is its own always-loaded system service, not tied to
     * a device family - unlike cdvdman.irx (loaded lazily by the
     * "cdrom0" device_mgr.c family below), a poweroff button should work
     * regardless of which devices are actually present. */
    SifLoadModule("host:modules/poweroff.irx", 0, NULL);
    poweroffInit();

    /* Device manager: lazily load + probe every family once at boot (M6's
     * scoping note still applies - only-load-on-navigation belongs to a
     * later UI-driven refresh, once there's more than one screen to
     * navigate between). */
    int familyCount;
    DeviceFamily *families = deviceMgrGetFamilies(&familyCount);
    int i;
    for (i = 0; i < familyCount; i++)
        deviceMgrRefresh(&families[i]);

    for (i = 0; i < familyCount; i++) {
        if (families[i].mountPrefix && families[i].available)
            scanDevice(families[i].mountPrefix);
    }

    /* stage2 is deployed unconditionally - every launch chains through it
     * regardless of which device the target itself lives on. Likewise,
     * always refresh target.elf's on-disk bytes to match this build:
     * this is this project's own trivial test stub (not a real user's
     * homebrew), so keeping it in sync every boot is the right call for
     * testing, even though a real dashboard should never silently
     * overwrite a user's actual app files. Refreshing the bytes is kept
     * separate from registering it as a browsable entry (below) - if the
     * scan above already found it, don't add it twice. */
    writeFile("mc0:/stage2.elf", stage2_elf, size_stage2_elf);
    writeFile("mc0:/target.elf", target_elf, size_target_elf);

    /* M10: deploy both embedded themes onto mc0: every boot too, exactly
     * like stage2/target above - keeps this project's own bundled themes
     * in sync with the build, and gives theme/theme.c a real on-disk
     * folder to load through fileXio rather than special-casing embedded
     * data in the loader itself.
     *
     * One directory level under root, not nested under a "themes/"
     * parent: the PS2 memory card filesystem only supports one level of
     * subdirectory below root at all (every real save folder - e.g.
     * "BASCUS-90123" - lives directly in MC root; mcman has no concept
     * of a folder-of-folders). A "mc0:/themes/dark/" layout is two
     * levels deep and silently fails to be created on MC. */
    ensureDir("mc0:/theme_dark");
    ensureDir("mc0:/theme_sunset");
    writeFile("mc0:/theme_dark/theme.cfg", theme_dark_cfg, size_theme_dark_cfg);
    writeFile("mc0:/theme_sunset/theme.cfg", theme_sunset_cfg, size_theme_sunset_cfg);

    /* Fallback so the browser always has something to show and launch
     * on a fresh memory card with no homebrew on it yet, in the (now
     * unlikely, since target.elf is always written above) case the scan
     * didn't already pick it up. */
    if (entryCount == 0) {
        const char *fallback = "mc0:/target.elf";
        char *dst = entries[0].path;
        while (*fallback)
            *dst++ = *fallback++;
        *dst = '\0';
        entryCount = 1;
    }

    /* M9: per-app metadata (launch count, favorite) - one small sibling
     * .cfg file per entry (config/metadata.c), loaded once at boot right
     * alongside the entries it describes. Missing or corrupt files both
     * degrade to all-zero defaults, so this never blocks the scan. */
    for (i = 0; i < entryCount; i++)
        metadataLoad(entries[i].path, &metas[i]);

    /* gsKit_init_global() auto-detects Mode/Interlace/Field/Width/Height -
     * confirmed working as-is since M1/M2, don't override. */
    GSGLOBAL *gsGlobal = gsKit_init_global();
    gsGlobal->PrimAlphaEnable = GS_SETTING_ON;

    dmaKit_init(D_CTRL_RELE_OFF, D_CTRL_MFD_OFF, D_CTRL_STS_UNSPEC,
                D_CTRL_STD_OFF, D_CTRL_RCYC_8, 1 << DMA_CHANNEL_GIF);
    dmaKit_chan_init(DMA_CHANNEL_GIF);

    gsKit_init_screen(gsGlobal);
    gsKit_mode_switch(gsGlobal, GS_ONESHOT);

    BitmapFont font;
    bitmapFontInit(&font, gsGlobal);

    /* M10: load both bundled themes once at boot (not per-switch) - a
     * theme's background texture, if any, is decoded and uploaded to
     * VRAM exactly once and simply referenced thereafter, so cycling
     * between themes at runtime never re-allocates VRAM (gsKit's
     * allocator has no free(), so repeated alloc-on-switch would
     * eventually exhaust the 4MB budget measured in M7). If a theme
     * fails to load (missing/corrupt files), it keeps a safe all-zero
     * struct - drawing with black tiles/labels rather than crashing. */
    if (themeLoad("mc0:/theme_dark/", &themes[0], gsGlobal) < 0)
        themeSetFallback(&themes[0]);
    if (themeLoad("mc0:/theme_sunset/", &themes[1], gsGlobal) < 0)
        themeSetFallback(&themes[1]);

    static char padBuf[256] __attribute__((aligned(64)));
    padInit(0);
    padPortOpen(0, 0, padBuf);

    /* Title-safe layout: keep every interactive/visible element within an
     * inset margin from the framebuffer edges, since the target displays
     * are CRT-era TVs with variable overscan (plan section 7). */
    float marginX = gsGlobal->Width * TITLE_SAFE_MARGIN;
    float marginY = gsGlobal->Height * TITLE_SAFE_MARGIN;
    float safeW = gsGlobal->Width - 2 * marginX;
    float safeBottom = gsGlobal->Height - marginY;

    /* M11: reserve one line at the bottom of the title-safe area for a
     * persistent disc-status/RTC readout - still within the safe-area
     * bounds, just carved out of the grid's own space rather than drawn
     * over top of it. */
    float statusLineHeight = 20.0f;
    safeBottom -= statusLineHeight;

    float gap = 16.0f;
    float cellSize = (safeW - (GRID_COLS - 1) * gap) / GRID_COLS;

    /* How many characters of a filename fit across one tile at 8px/char,
     * leaving a little breathing room on each side - truncated labels
     * beat labels that overflow into the next tile. */
    int maxLabelChars = (int)(cellSize / 8.0f) - 1;
    if (maxLabelChars < 1)
        maxLabelChars = 1;
    if (maxLabelChars > 63)
        maxLabelChars = 63;

    int focus = 0;
    u32 prevPressed = 0;

    /* M11: disc status/RTC are polled roughly once a second, not every
     * frame - both go over SIF RPC to the IOP, and a status line that's
     * a second stale is unnoticeable while sixty extra RPC round-trips a
     * second for no visible benefit isn't free (plan section 10). ~60
     * frames is an approximation (NTSC is actually 59.94, PAL is 50) -
     * fine for a once-a-second cosmetic refresh. */
    int statusFrameCounter = 0;
    static char statusLine[64] __attribute__((aligned(64)));
    static char statusLinePending[64] __attribute__((aligned(64)));
    statusLine[0] = '\0';
    statusLinePending[0] = '\0';

    /* Diagnostic step: instead of re-rendering this text at the same
     * screen position on every single frame (~60x/sec) even when its
     * content hasn't changed, only (re)draw it for a few frames right
     * after it actually changes, then leave the already-correct pixels
     * alone. If that resolves the glitching, repeated identical redraws
     * at this position were themselves the trigger - something none of
     * the earlier GS-state fixes (blend/test/alignment/UV inset)
     * addressed, since those didn't change how OFTEN the draw happened.
     * Redraw for a few frames, not just one, so the text still reaches
     * every buffer in whatever multi-buffering gsKit is doing under the
     * hood - drawing it only once could leave a stale copy in a buffer
     * that isn't shown again for another frame or two. */
    int statusRedrawFramesLeft = 0;

    while (1) {
        if (statusFrameCounter == 0) {
            /* sceCdReadClock() fills this via a SIF RPC - the IOP DMAs
             * its response back into EE memory. An unaligned/unpadded
             * stack struct here lets that DMA touch a whole 64-byte
             * cache line, which can silently clobber whatever *other*
             * stack variables happen to share it - not just this 8-byte
             * struct. Exactly the padBuf/SIO2 gotcha above, applied to a
             * different IOP driver: static+aligned gives it a dedicated
             * cache line the compiler won't pack anything else into
             * (confirmed real: this was corrupting statusLine's own text
             * once a second, right when this RPC ran). */
            static sceCdCLOCK clock __attribute__((aligned(64)));
            int diskType = sceCdGetDiskType();
            if (sceCdReadClock(&clock)) {
                sprintf(statusLinePending, "%s | 20%02d-%02d-%02d %02d:%02d:%02d", diskTypeName(diskType),
                        bcdToDec(clock.year), bcdToDec(clock.month), bcdToDec(clock.day), bcdToDec(clock.hour),
                        bcdToDec(clock.minute), bcdToDec(clock.second));
            } else {
                sprintf(statusLinePending, "%s | RTC unavailable", diskTypeName(diskType));
            }
            if (strcmp(statusLinePending, statusLine) != 0) {
                strcpy(statusLine, statusLinePending);
                statusRedrawFramesLeft = 3;
            }
        }
        statusFrameCounter = (statusFrameCounter + 1) % 60;

        u32 pressed = 0;
        if (padGetState(0, 0) == PAD_STATE_STABLE) {
            struct padButtonStatus buttons;
            padRead(0, 0, &buttons);
            pressed = 0xffff ^ buttons.btns;
        }
        u32 edge = pressed & ~prevPressed;
        prevPressed = pressed;

        /* M11: SELECT is a real, immediate system poweroff - not
         * expected to "return" to the loop on hardware, but PCSX2's own
         * behavior when a homebrew ELF calls this is untested territory
         * for this project, so no assumption is made about what happens
         * next. */
        if (edge & PAD_SELECT)
            poweroffShutdown();

        /* M10: L1/R1 cycle between the bundled themes at runtime -
         * switching is just changing which already-loaded Theme struct
         * is "current" (see the boot-time themeLoad() calls above), so
         * it's instant and allocates no new VRAM. */
        if (edge & PAD_R1)
            currentTheme = (currentTheme + 1) % THEME_COUNT;
        if (edge & PAD_L1)
            currentTheme = (currentTheme - 1 + THEME_COUNT) % THEME_COUNT;
        Theme *theme = &themes[currentTheme];

        if (entryCount > 0) {
            if (edge & PAD_RIGHT)
                focus = (focus + 1) % entryCount;
            if (edge & PAD_LEFT)
                focus = (focus - 1 + entryCount) % entryCount;
            if (edge & PAD_DOWN) {
                int n = focus + GRID_COLS;
                if (n < entryCount)
                    focus = n;
            }
            if (edge & PAD_UP) {
                int n = focus - GRID_COLS;
                if (n >= 0)
                    focus = n;
            }
            if (edge & PAD_TRIANGLE) {
                metas[focus].favorite = !metas[focus].favorite;
                metadataSave(entries[focus].path, &metas[focus]);
            }
            if (edge & PAD_CROSS) {
                /* Persist the launch before handing off, not after - a
                 * successful launch never returns here to record it. */
                metas[focus].launchCount++;
                metadataSave(entries[focus].path, &metas[focus]);

                char *stage2Argv[2];
                stage2Argv[0] = entries[focus].path;
                stage2Argv[1] = "0"; /* reset_iop: false, the common case */
                elfLoadAndExec("mc0:/stage2.elf", 0, 2, stage2Argv);
                /* Not expected to return - if it does, the launch failed;
                 * fall through and keep the browser up rather than
                 * hanging (plan section 11's fallback philosophy). */
            }
        }

        /* The routine per-frame clear stops at safeBottom now, leaving
         * the status-line strip below it untouched except on the few
         * frames right after its text actually changes (below) - part of
         * the same diagnostic: a region that's touched every frame vs.
         * one that's only touched on real change. */
        if (theme->hasBackground) {
            /* Stretched to fill the whole screen via UV mapping - the
             * background's own baked pixel size doesn't need to match
             * gsGlobal's runtime-detected resolution (theme/theme.c).
             * Textured draws need the M7-confirmed blend-equation setup
             * (PrimAlphaEnable alone isn't enough), same as bitmap_font.c.
             * v1 is scaled to match the shortened destination height so
             * the image doesn't stretch differently than intended - moot
             * today since no bundled theme actually has a background. */
            gsKit_set_primalpha(gsGlobal, GS_SETREG_ALPHA(0, 1, 0, 1, 0), 0);
            gsKit_set_test(gsGlobal, GS_ATEST_OFF);
            /* Neutral modulation: RGB 0xFF (matches bitmap_font.c's pure-
             * white glyph pixels needing 0xFF to render untinted) and
             * alpha 0x80, the GS's own 7-bit "fully opaque" value - not
             * 0x80,0x80,0x80, which would multiplicatively halve the
             * background's brightness. */
            gsKit_prim_sprite_texture(gsGlobal, &theme->background, 0.0f, 0.0f, 0.0f, 0.0f, (float)gsGlobal->Width,
                                       safeBottom, (float)theme->background.Width,
                                       (float)theme->background.Height * (safeBottom / (float)gsGlobal->Height), 0,
                                       GS_SETREG_RGBAQ(0xFF, 0xFF, 0xFF, 0x80, 0x00));
            gsKit_set_test(gsGlobal, GS_ATEST_ON);
            gsKit_set_primalpha(gsGlobal, GS_BLEND_BACK2FRONT, 0);
        } else {
            /* Every theme color here (bg/tile/focus) uses alpha=0x00 -
             * never meant as "transparent", just "unused" on a flat-
             * shaded, non-textured primitive. Disabling blending (below)
             * wasn't enough on its own: alpha TESTING is a separate,
             * earlier pipeline stage, and bitmapFontPrint() leaves
             * GS_ATEST_ON as its "resting" state after every text draw.
             * If that mode is configured to reject alpha=0 fragments
             * (common for punch-through masking), every pixel of this
             * fill gets discarded before blending is ever considered -
             * explaining why disabling PrimAlphaEnable alone didn't fix
             * the earlier ghosting. Disabling the alpha test too
             * guarantees this fill actually writes. */
            gsGlobal->PrimAlphaEnable = GS_SETTING_OFF;
            gsKit_set_test(gsGlobal, GS_ATEST_OFF);
            gsKit_prim_sprite(gsGlobal, 0.0f, 0.0f, (float)gsGlobal->Width, safeBottom, 0, theme->bgColor);
            gsKit_set_test(gsGlobal, GS_ATEST_ON);
            gsGlobal->PrimAlphaEnable = GS_SETTING_ON;
        }

        for (i = 0; i < entryCount; i++) {
            int col = i % GRID_COLS;
            int row = i / GRID_COLS;
            float x = marginX + col * (cellSize + gap);
            float y = marginY + row * (cellSize + gap);

            if (y + cellSize > safeBottom)
                break; /* no scrolling yet - a later milestone's problem */

            /* Same defensive opaque-fill guard as the background clear
             * above - both blending AND alpha testing disabled, since a
             * flat-shaded alpha=0x00 fill shouldn't be exposed to
             * whatever state the last text draw left either stage in. */
            gsGlobal->PrimAlphaEnable = GS_SETTING_OFF;
            gsKit_set_test(gsGlobal, GS_ATEST_OFF);
            gsKit_prim_sprite(gsGlobal, x, y, x + cellSize, y + cellSize, 1,
                               i == focus ? theme->focusColor : theme->tileColor);
            gsKit_set_test(gsGlobal, GS_ATEST_ON);
            gsGlobal->PrimAlphaEnable = GS_SETTING_ON;

            /* Build the full "[*]name (count)" string first, then
             * truncate to whatever fits the tile - a favorited, heavily-
             * launched entry should lose its count/name tail before it
             * loses the favorite marker, which is why the marker is
             * prepended rather than appended. */
            char full[80];
            int fi = 0;
            if (metas[i].favorite)
                full[fi++] = '*';
            const char *name = baseName(entries[i].path);
            while (*name && fi < 60)
                full[fi++] = *name++;
            if (metas[i].launchCount > 0 && fi < 70)
                fi += sprintf(full + fi, " (%d)", metas[i].launchCount);
            full[fi] = '\0';

            char label[64];
            int len = 0;
            while (full[len] && len < maxLabelChars)
                len++;
            memcpy(label, full, len);
            label[len] = '\0';

            bitmapFontPrint(gsGlobal, &font, x + 4.0f, y + cellSize - 20.0f, theme->labelColor, label);
        }

        if (statusRedrawFramesLeft > 0) {
            /* Explicit strip clear, since the routine full-screen fill
             * above now deliberately stops at safeBottom and never
             * touches this area - it must be cleared here instead,
             * right before (re)drawing the text, using the same
             * guaranteed-opaque guards. */
            gsGlobal->PrimAlphaEnable = GS_SETTING_OFF;
            gsKit_set_test(gsGlobal, GS_ATEST_OFF);
            gsKit_prim_sprite(gsGlobal, 0.0f, safeBottom, (float)gsGlobal->Width, (float)gsGlobal->Height, 0,
                               theme->bgColor);
            gsKit_set_test(gsGlobal, GS_ATEST_ON);
            gsGlobal->PrimAlphaEnable = GS_SETTING_ON;

            bitmapFontPrint(gsGlobal, &font, marginX, safeBottom + 2.0f, theme->labelColor, statusLine);
            statusRedrawFramesLeft--;
        }

        gsKit_queue_exec(gsGlobal);
        gsKit_sync_flip(gsGlobal);
    }

    return 0;
}
