#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <gsKit.h>
#include <dmaKit.h>
#include <libpad.h>
#include <string.h>
#include <stdio.h>
#include <libcdvd.h>
#include <libpwroff.h>

#define NEWLIB_PORT_AWARE
#include <fileXio_rpc.h>
#include <iox_stat.h>
#include <io_common.h>

#include "../common/elfloader.h"
#include "device/device_mgr.h"
#include "gfx/bitmap_font.h"
#include "config/metadata.h"
#include "theme/theme.h"
#include "log/log.h"

/* M10: two embedded themes (colors + an optional background image),
 * deployed onto mc0: at boot the same way target.elf/stage2.elf already
 * are (see the extern block below main() and writeFile() calls) so
 * theme.cfg/background.png are loaded back through the real fileXio
 * path-based loader (theme/theme.c) rather than special-cased in code -
 * proving the same asset-loading pipeline a real, user-supplied theme
 * folder would go through. */
extern unsigned char theme_dark_cfg[];
extern unsigned int size_theme_dark_cfg;
extern unsigned char theme_sunset_cfg[];
extern unsigned int size_theme_sunset_cfg;

#define THEME_COUNT 2
static Theme themes[THEME_COUNT];
static int currentTheme = 0;

/* M11: system services (plan section 9) - disc status/RTC read via
 * libcdvd (cdvdman.irx is already loaded by device_mgr.c's "cdrom0"
 * family refresh, so no extra module load is needed here beyond
 * poweroff.irx itself), plus a real poweroff wired to a pad button. */
static int bcdToDec(u8 bcd)
{
    return ((bcd >> 4) * 10) + (bcd & 0x0F);
}

static const char *diskTypeName(int type)
{
    switch (type) {
    case SCECdNODISC:
        return "no disc";
    case SCECdDETCT:
    case SCECdDETCTCD:
    case SCECdDETCTDVDS:
    case SCECdDETCTDVDD:
        return "detecting";
    case SCECdPSCD:
    case SCECdPSCDDA:
        return "PS1 CD";
    case SCECdPS2CD:
    case SCECdPS2CDDA:
        return "PS2 CD";
    case SCECdPS2DVD:
        return "PS2 DVD";
    case SCECdCDDA:
        return "audio CD";
    case SCECdDVDV:
        return "DVD video";
    case SCECdIllegalMedia:
        return "illegal media";
    default:
        return "unknown";
    }
}

/* Bytes of the built target.elf / stage2.elf, generated by bin2c (see
 * embedded/target_elf.c, embedded/stage2_elf.c) - stage2.elf is always
 * deployed by the dashboard itself (it's the same regardless of which
 * device the actual target lives on); target.elf is only written as a
 * fallback so the browser always has at least one real, launchable
 * entry to demonstrate against on a fresh memory card. */
extern unsigned char target_elf[];
extern unsigned int size_target_elf;
extern unsigned char stage2_elf[];
extern unsigned int size_stage2_elf;

/* M8 note: this is the first milestone with a real, navigable dashboard
 * UI - a grid of launchable ELF entries scanned across every available
 * device family (M6), rendered with gsKit (M1/M2/M7's proven patterns),
 * driven by the pad (M1/M2). Text labels were a deliberate, documented
 * gap in M8 (gsKit's own font system loads glyph sheets by path, hitting
 * the same POSIX/fopen device-table gap confirmed in M4/M7) - closed at
 * the start of M9 using wLaunchELF's bitmap font data (gfx/font_uLE.c,
 * gfx/bitmap_font.c), decoded directly into a GS texture atlas the same
 * way M7's icon atlas works, sidestepping gsKit's path-based loader
 * entirely rather than fighting the same fileXio-vs-fopen issue again. */

#define GRID_COLS 4
#define MAX_ENTRIES 32
#define TITLE_SAFE_MARGIN 0.08f

typedef struct {
    char path[256];
} AppEntry;

/* Used only if a theme fails to load entirely (missing/corrupt files) -
 * an all-zero Theme would render solid black on black, indistinguishable
 * from a real hang/crash. Matches the M8/M9 hardcoded colors this
 * project shipped before M10, so a theme-load failure degrades to
 * "looks like before", never to "looks broken" (plan section 11). */
static void themeSetFallback(Theme *t)
{
    memset(t, 0, sizeof(*t));
    t->bgColor = GS_SETREG_RGBAQ(0x10, 0x10, 0x14, 0x00, 0x00);
    t->tileColor = GS_SETREG_RGBAQ(0x30, 0x30, 0x38, 0x00, 0x00);
    t->focusColor = GS_SETREG_RGBAQ(0x60, 0x80, 0xC0, 0x00, 0x00);
    t->labelColor = GS_SETREG_RGBAQ(0x80, 0x80, 0x80, 0x80, 0x00);
}

static AppEntry entries[MAX_ENTRIES];
static AppMetadata metas[MAX_ENTRIES];
static int entryCount = 0;

static int hasElfExtension(const char *name)
{
    int len = 0;
    while (name[len])
        len++;
    if (len < 4)
        return 0;
    const char *e = name + len - 4;
    return e[0] == '.' && (e[1] == 'e' || e[1] == 'E') && (e[2] == 'l' || e[2] == 'L') &&
           (e[3] == 'f' || e[3] == 'F');
}

/* stage2.elf is this launcher's own internal chain-load stub (see
 * elfloader.h / stage2/main.c) - it's real, and it does match the .elf
 * filter, but it's not a user-selectable app, and launching it directly
 * (as if it were a target) makes it try to re-launch itself, which
 * produced inconsistent/crashing results during the M8 spike. Excluded
 * by name specifically, rather than never writing it to a real device,
 * since a real device is exactly where it needs to live for chain-
 * loading to work at all. */
static int isInternalPlumbingFile(const char *name)
{
    static const char *target = "stage2.elf";
    int i;
    for (i = 0; target[i]; i++) {
        char c = name[i];
        if (c >= 'A' && c <= 'Z')
            c += 'a' - 'A';
        if (c != target[i])
            return 0;
    }
    return name[i] == '\0';
}

/* Scans one device's root directory for .elf/.ELF entries. prefix is
 * expected to already end in '/' (matches every mountPrefix in
 * device_mgr.c), so paths concatenate directly. */
static void scanDevice(const char *prefix)
{
    iox_stat_t st;
    if (fileXioGetStat(prefix, &st) < 0)
        return;

    int fd = fileXioDopen(prefix);
    if (fd < 0)
        return;

    iox_dirent_t dirent;
    while (fileXioDread(fd, &dirent) > 0) {
        if (FIO_S_ISDIR(dirent.stat.mode))
            continue;
        if (!hasElfExtension(dirent.name))
            continue;
        if (isInternalPlumbingFile(dirent.name))
            continue;
        if (entryCount >= MAX_ENTRIES)
            break;

        char *dst = entries[entryCount].path;
        const char *p = prefix;
        while (*p)
            *dst++ = *p++;
        const char *n = dirent.name;
        while (*n)
            *dst++ = *n++;
        *dst = '\0';
        entryCount++;
    }
    fileXioDclose(fd);
}

/* Returns a pointer into `path` just past its last ':' or '/' - e.g.
 * "mc0:/target.elf" -> "target.elf". Never allocates; the result aliases
 * the input. */
static const char *baseName(const char *path)
{
    const char *base = path;
    const char *p = path;
    while (*p) {
        if (*p == ':' || *p == '/')
            base = p + 1;
        p++;
    }
    return base;
}

/* Real PS2 game discs don't have a "*.elf" file anywhere on them - the
 * scan above would never find one - but the actual boot executable they
 * reference IS a genuine ELF binary, just under an arbitrary filename
 * (e.g. "SLUS_123.45"). SYSTEM.CNF at the disc root names it:
 *   BOOT2 = cdrom0:\SLUS_123.45;1
 * elfLoadAndExec() only ever validated ELF magic, never the filename, so
 * once this path is known it launches exactly like any other entry - no
 * new loader logic needed, only a different way to discover the path.
 * PS1 discs use "BOOT" (no "2") and a completely different, non-ELF
 * executable format requiring PS1 BIOS compatibility mode on real
 * hardware - out of scope, and this function's "BOOT2"-only match
 * naturally skips them rather than finding a path we couldn't load
 * anyway. Returns 0 and fills out (converting backslashes to forward
 * slashes; the ";N" ISO9660 version suffix is kept as-is since cdrom0:
 * needs it to resolve the file) on success. */
/* fileXioOpen()/fileXioDopen()+fileXioDread() against cdrom0: turned out
 * unreliable in practice - fileXioGetStat() on the root succeeds (that's
 * how device_mgr.c's probeFs() sees the family as available at all), but
 * both a direct SYSTEM.CNF open and a root directory listing failed
 * outright, confirmed via live PCSX2 memory reads. cdvdfsv's fileXio
 * compatibility layer apparently doesn't fully cover file lookup/listing
 * the way it does for MC/USB's FAT-style drivers. libcdvd's own,
 * CD-specific file API - sceCdSearchFile() + sceCdRead() - is what
 * wLaunchELF/OPL actually use for this, and doesn't go through
 * fileXio/iomanX at all. Confirmed working end-to-end against a real
 * PS2 disc (SYSTEM.CNF found, read, and parsed to a real boot path). */
static int parseDiscBootPath(char *out, int outSize)
{
    sceCdlFILE file;
    if (!sceCdSearchFile(&file, "\\SYSTEM.CNF;1"))
        return -1;

    unsigned int sectors = (file.size + 2047) / 2048;
    if (sectors == 0)
        sectors = 1;
    if (sectors > 4) /* SYSTEM.CNF is always a handful of lines - guard against a bogus size */
        sectors = 4;

    static unsigned char cdBuf[4 * 2048] __attribute__((aligned(64)));
    static sceCdRMode mode;
    mode.trycount = 0;
    mode.spindlctrl = 0;
    mode.datapattern = SCECdSecS2048;
    mode.pad = 0;

    if (!sceCdRead(file.lsn, sectors, cdBuf, &mode))
        return -1;
    sceCdSync(0); /* sceCdRead is non-blocking - this is the documented way to wait for it */

    unsigned int n = file.size;
    if (n >= sizeof(cdBuf))
        n = sizeof(cdBuf) - 1;
    cdBuf[n] = '\0';

    char *line = strtok((char *)cdBuf, "\r\n");
    while (line) {
        if (strncmp(line, "BOOT2", 5) == 0) {
            char *eq = strchr(line, '=');
            if (!eq)
                return -1;
            char *p = eq + 1;
            while (*p == ' ')
                p++;
            int i = 0;
            while (*p && *p != ' ' && *p != '\t' && i < outSize - 1) {
                out[i++] = (*p == '\\') ? '/' : *p;
                p++;
            }
            out[i] = '\0';
            return (i > 0) ? 0 : -1;
        }
        line = strtok(NULL, "\r\n");
    }
    return -1;
}

static int writeFile(const char *path, const void *data, unsigned int size)
{
    int fd = fileXioOpen(path, FIO_O_WRONLY | FIO_O_CREAT | FIO_O_TRUNC, 0666);
    if (fd < 0)
        return fd;
    int written = fileXioWrite(fd, data, size);
    fileXioClose(fd);
    return (written == (int)size) ? 0 : -1;
}

/* fileXioMkdir fails (harmlessly) if the directory already exists - not
 * checked, since either way the writeFile() calls right after this are
 * what actually determine success. */
static void ensureDir(const char *path)
{
    fileXioMkdir(path, 0777);
}

/* M13 (plan section 11, "removed storage mid-browse"): rebuilds entries[]
 * from scratch against the families' *current* available state - shared
 * by the boot-time scan and the periodic mid-session rescan below, so a
 * device pulled or reinserted after boot is actually reflected in the
 * browsable grid, not just safely failing if launched (which was already
 * true before this, just not proactive). Assumes stage2.elf/target.elf
 * are already on mc0: (main() writes them before ever calling this) -
 * the entryCount==0 fallback path below depends on target.elf actually
 * existing by this point. */
static void rescanEntries(DeviceFamily *families, int familyCount)
{
    entryCount = 0;

    int i;
    for (i = 0; i < familyCount; i++) {
        if (families[i].mountPrefix && families[i].available)
            scanDevice(families[i].mountPrefix);
    }

    /* A real game disc, if one's mounted, needs its own discovery path
     * (see parseDiscBootPath()'s header comment) rather than the
     * extension-based scan above, which will never find anything on
     * commercial disc media. */
    for (i = 0; i < familyCount; i++) {
        if (strcmp(families[i].name, "cdrom0") == 0 && families[i].available) {
            if (entryCount < MAX_ENTRIES && parseDiscBootPath(entries[entryCount].path, sizeof(entries[0].path)) == 0)
                entryCount++;
            break;
        }
    }

    /* Fallback so the browser always has something to show and launch
     * on a fresh memory card with no homebrew on it yet. */
    if (entryCount == 0) {
        const char *fallback = "mc0:/target.elf";
        char *dst = entries[0].path;
        while (*fallback)
            *dst++ = *fallback++;
        *dst = '\0';
        entryCount = 1;
    }

    /* M9: per-app metadata (launch count, favorite) - one small sibling
     * .cfg file per entry (config/metadata.c). Missing or corrupt files
     * both degrade to all-zero defaults, so this never blocks the scan. */
    for (i = 0; i < entryCount; i++)
        metadataLoad(entries[i].path, &metas[i]);
}

int main(int argc, char *argv[])
{
    SifInitRpc(0);

    SifLoadModule("rom0:SIO2MAN", 0, NULL);
    SifLoadModule("rom0:PADMAN", 0, NULL);
    SifLoadModule("host:modules/iomanX.irx", 0, NULL);
    SifLoadModule("host:modules/fileXio.irx", 0, NULL);
    fileXioInit();
    fileXioSetRWBufferSize(128 * 1024);

    logInit();
    logMsg("boot: dashboard starting");

    /* M11: poweroff is its own always-loaded system service, not tied to
     * a device family - unlike cdvdman.irx (loaded lazily by the
     * "cdrom0" device_mgr.c family below), a poweroff button should work
     * regardless of which devices are actually present. */
    SifLoadModule("host:modules/poweroff.irx", 0, NULL);
    poweroffInit();

    /* Device manager: lazily load + probe every family once at boot (M6's
     * scoping note still applies - only-load-on-navigation belongs to a
     * later UI-driven refresh, once there's more than one screen to
     * navigate between). */
    int familyCount;
    DeviceFamily *families = deviceMgrGetFamilies(&familyCount);
    int i;
    for (i = 0; i < familyCount; i++)
        deviceMgrRefresh(&families[i]);

    /* stage2 is deployed unconditionally - every launch chains through it
     * regardless of which device the target itself lives on. Likewise,
     * always refresh target.elf's on-disk bytes to match this build:
     * this is this project's own trivial test stub (not a real user's
     * homebrew), so keeping it in sync every boot is the right call for
     * testing, even though a real dashboard should never silently
     * overwrite a user's actual app files. Refreshing the bytes is kept
     * separate from registering it as a browsable entry - rescanEntries()
     * below finds it as a normal scanned entry once it's actually there. */
    writeFile("mc0:/stage2.elf", stage2_elf, size_stage2_elf);
    writeFile("mc0:/target.elf", target_elf, size_target_elf);

    /* M10: deploy both embedded themes onto mc0: every boot too, exactly
     * like stage2/target above - keeps this project's own bundled themes
     * in sync with the build, and gives theme/theme.c a real on-disk
     * folder to load through fileXio rather than special-casing embedded
     * data in the loader itself.
     *
     * One directory level under root, not nested under a "themes/"
     * parent: the PS2 memory card filesystem only supports one level of
     * subdirectory below root at all (every real save folder - e.g.
     * "BASCUS-90123" - lives directly in MC root; mcman has no concept
     * of a folder-of-folders). A "mc0:/themes/dark/" layout is two
     * levels deep and silently fails to be created on MC. */
    ensureDir("mc0:/theme_dark");
    ensureDir("mc0:/theme_sunset");
    writeFile("mc0:/theme_dark/theme.cfg", theme_dark_cfg, size_theme_dark_cfg);
    writeFile("mc0:/theme_sunset/theme.cfg", theme_sunset_cfg, size_theme_sunset_cfg);

    rescanEntries(families, familyCount);

    /* gsKit_init_global() auto-detects Mode/Interlace/Field/Width/Height -
     * confirmed working as-is since M1/M2, don't override. */
    GSGLOBAL *gsGlobal = gsKit_init_global();
    gsGlobal->PrimAlphaEnable = GS_SETTING_ON;

    dmaKit_init(D_CTRL_RELE_OFF, D_CTRL_MFD_OFF, D_CTRL_STS_UNSPEC,
                D_CTRL_STD_OFF, D_CTRL_RCYC_8, 1 << DMA_CHANNEL_GIF);
    dmaKit_chan_init(DMA_CHANNEL_GIF);

    gsKit_init_screen(gsGlobal);
    gsKit_mode_switch(gsGlobal, GS_ONESHOT);

    /* M13: bitmapFontInit() can fail (VRAM exhaustion, allocation
     * failure) - previously discarded entirely, so a failure here would
     * have left every later bitmapFontPrint() call drawing through an
     * uninitialized/zeroed BitmapFont (a texture with Vram=0, aliasing
     * the framebuffer). fontOk gates every text draw below so a failure
     * degrades to a text-free but otherwise fully functional UI (tiles,
     * launching, navigation all still work) instead of corrupting the
     * framebuffer. */
    BitmapFont font;
    int fontOk = (bitmapFontInit(&font, gsGlobal) == 0);
    if (!fontOk)
        logMsg("font init failed, running text-free");

    /* M10: load both bundled themes once at boot (not per-switch) - a
     * theme's background texture, if any, is decoded and uploaded to
     * VRAM exactly once and simply referenced thereafter, so cycling
     * between themes at runtime never re-allocates VRAM (gsKit's
     * allocator has no free(), so repeated alloc-on-switch would
     * eventually exhaust the 4MB budget measured in M7). If a theme
     * fails to load (missing/corrupt files), it keeps a safe all-zero
     * struct - drawing with black tiles/labels rather than crashing. */
    if (themeLoad("mc0:/theme_dark/", &themes[0], gsGlobal) < 0) {
        themeSetFallback(&themes[0]);
        logMsg("theme load failed: dark, using fallback colors");
    }
    if (themeLoad("mc0:/theme_sunset/", &themes[1], gsGlobal) < 0) {
        themeSetFallback(&themes[1]);
        logMsg("theme load failed: sunset, using fallback colors");
    }

    static char padBuf[256] __attribute__((aligned(64)));
    padInit(0);
    padPortOpen(0, 0, padBuf);

    /* Title-safe layout: keep every interactive/visible element within an
     * inset margin from the framebuffer edges, since the target displays
     * are CRT-era TVs with variable overscan (plan section 7). */
    float marginX = gsGlobal->Width * TITLE_SAFE_MARGIN;
    float marginY = gsGlobal->Height * TITLE_SAFE_MARGIN;
    float safeW = gsGlobal->Width - 2 * marginX;
    float safeBottom = gsGlobal->Height - marginY;

    /* M11: reserve one line at the bottom of the title-safe area for a
     * persistent disc-status/RTC readout - still within the safe-area
     * bounds, just carved out of the grid's own space rather than drawn
     * over top of it. */
    float statusLineHeight = 20.0f;
    safeBottom -= statusLineHeight;

    float gap = 16.0f;
    float cellSize = (safeW - (GRID_COLS - 1) * gap) / GRID_COLS;

    /* How many characters of a filename fit across one tile at 8px/char,
     * leaving a little breathing room on each side - truncated labels
     * beat labels that overflow into the next tile. */
    int maxLabelChars = (int)(cellSize / 8.0f) - 1;
    if (maxLabelChars < 1)
        maxLabelChars = 1;
    if (maxLabelChars > 63)
        maxLabelChars = 63;

    int focus = 0;
    u32 prevPressed = 0;

    /* M13 (plan section 11's own explicit task, "logging/debug overlay") -
     * START was unused (SELECT is poweroff, L1/R1 are themes, TRIANGLE is
     * favorite, CROSS launches, D-pad navigates). */
    int overlayVisible = 0;
    int debugLoggingOn = 0; /* mc0:/launcher.log disk flush - off by default, toggled with SQUARE on the overlay */

    /* M11: disc status/RTC are polled roughly once a second, not every
     * frame - both go over SIF RPC to the IOP, and a status line that's
     * a second stale is unnoticeable while sixty extra RPC round-trips a
     * second for no visible benefit isn't free (plan section 10). ~60
     * frames is an approximation (NTSC is actually 59.94, PAL is 50) -
     * fine for a once-a-second cosmetic refresh. */
    int statusFrameCounter = 0;
    static char statusLine[64] __attribute__((aligned(64)));
    statusLine[0] = '\0';

    /* M13 (plan section 11): both of these were previously silent - a
     * failed launch (bad ELF, or its device removed since the boot-time
     * scan) or a disconnected controller left the UI looking frozen,
     * indistinguishable from an actual hang. Both reuse the status
     * line's existing render slot rather than adding a new one -
     * disconnect takes priority over a launch-failure message, since
     * it's the more pressing state and also because a disconnected pad
     * can't be the one that just triggered a launch attempt anyway. */
    char overrideMsg[64];
    int launchFailedFramesLeft = 0;
    int disconnectFrames = 0;

    /* M13 (plan section 11, "removed storage mid-browse"): a lightweight
     * recheck of removable-media families every ~3 seconds (180 frames) -
     * long enough to be cheap (this is a real IOP RPC per family, not
     * free), short enough that pulling a USB stick or swapping a disc
     * gets reflected in the browsable grid without needing to wait long
     * or trigger it by trying to launch something. Only families with a
     * quickProbe are ever rechecked - see device_mgr.h. */
    int rescanFrameCounter = 0;

    while (1) {
        if (rescanFrameCounter == 0) {
            int changed = 0;
            for (i = 0; i < familyCount; i++) {
                int wasAvailable = families[i].available;
                deviceMgrQuickRescan(&families[i]);
                if (families[i].available != wasAvailable)
                    changed = 1;
            }
            if (changed) {
                rescanEntries(families, familyCount);
                if (focus >= entryCount)
                    focus = (entryCount > 0) ? entryCount - 1 : 0;
            }
        }
        rescanFrameCounter = (rescanFrameCounter + 1) % 180;

        if (statusFrameCounter == 0) {
            /* sceCdReadClock() fills this via a SIF RPC - the IOP DMAs
             * its response back into EE memory. An unaligned/unpadded
             * stack struct here lets that DMA touch a whole 64-byte
             * cache line, which can silently clobber whatever *other*
             * stack variables happen to share it - not just this 8-byte
             * struct. Exactly the padBuf/SIO2 gotcha above, applied to a
             * different IOP driver: static+aligned gives it a dedicated
             * cache line the compiler won't pack anything else into
             * (confirmed real: this was corrupting statusLine's own text
             * once a second, right when this RPC ran). */
            static sceCdCLOCK clock __attribute__((aligned(64)));
            int diskType = sceCdGetDiskType();
            if (sceCdReadClock(&clock)) {
                sprintf(statusLine, "%s | 20%02d-%02d-%02d %02d:%02d:%02d", diskTypeName(diskType),
                        bcdToDec(clock.year), bcdToDec(clock.month), bcdToDec(clock.day), bcdToDec(clock.hour),
                        bcdToDec(clock.minute), bcdToDec(clock.second));
            } else {
                sprintf(statusLine, "%s | RTC unavailable", diskTypeName(diskType));
            }
        }
        statusFrameCounter = (statusFrameCounter + 1) % 60;

        u32 pressed = 0;
        if (padGetState(0, 0) == PAD_STATE_STABLE) {
            struct padButtonStatus buttons;
            padRead(0, 0, &buttons);
            pressed = 0xffff ^ buttons.btns;
            if (disconnectFrames > 30)
                logMsg("controller reconnected");
            disconnectFrames = 0;
        } else {
            /* A handful of not-stable frames is normal (between reads,
             * brief bus contention) - only treat it as a real disconnect
             * once it's sustained for about half a second, so momentary
             * blips don't flash the message or spam the log. */
            if (disconnectFrames == 30)
                logMsg("controller disconnected");
            if (disconnectFrames < 1000000)
                disconnectFrames++;
        }
        u32 edge = pressed & ~prevPressed;
        prevPressed = pressed;

        if (edge & PAD_START)
            overlayVisible = !overlayVisible;

        /* SQUARE explicitly toggles the mc0:/launcher.log disk flush
         * on/off (see log.c) - only live while the overlay is showing,
         * so it can't be toggled by accident during normal navigation.
         * Deliberately separate from just viewing the overlay: opening
         * it to glance at recent events shouldn't itself start writing
         * to MC on every device probe/launch, per the user's own call
         * that those are two different decisions. */
        if (overlayVisible && (edge & PAD_SQUARE)) {
            debugLoggingOn = !debugLoggingOn;
            logSetDebugEnabled(debugLoggingOn);
        }

        /* M11: SELECT is a real, immediate system poweroff - not
         * expected to "return" to the loop on hardware, but PCSX2's own
         * behavior when a homebrew ELF calls this is untested territory
         * for this project, so no assumption is made about what happens
         * next. */
        if (edge & PAD_SELECT)
            poweroffShutdown();

        /* M10: L1/R1 cycle between the bundled themes at runtime -
         * switching is just changing which already-loaded Theme struct
         * is "current" (see the boot-time themeLoad() calls above), so
         * it's instant and allocates no new VRAM. */
        if (edge & PAD_R1)
            currentTheme = (currentTheme + 1) % THEME_COUNT;
        if (edge & PAD_L1)
            currentTheme = (currentTheme - 1 + THEME_COUNT) % THEME_COUNT;
        Theme *theme = &themes[currentTheme];

        if (entryCount > 0) {
            if (edge & PAD_RIGHT)
                focus = (focus + 1) % entryCount;
            if (edge & PAD_LEFT)
                focus = (focus - 1 + entryCount) % entryCount;
            if (edge & PAD_DOWN) {
                int n = focus + GRID_COLS;
                if (n < entryCount)
                    focus = n;
            }
            if (edge & PAD_UP) {
                int n = focus - GRID_COLS;
                if (n >= 0)
                    focus = n;
            }
            if (edge & PAD_TRIANGLE) {
                metas[focus].favorite = !metas[focus].favorite;
                metadataSave(entries[focus].path, &metas[focus]);
            }
            if (edge & PAD_CROSS) {
                /* Persist the launch before handing off, not after - a
                 * successful launch never returns here to record it. */
                metas[focus].launchCount++;
                metadataSave(entries[focus].path, &metas[focus]);

                logMsg("launching: %s", entries[focus].path);

                char *stage2Argv[2];
                stage2Argv[0] = entries[focus].path;
                stage2Argv[1] = "0"; /* reset_iop: false, the common case */
                elfLoadAndExec("mc0:/stage2.elf", 0, 2, stage2Argv);
                /* Not expected to return - if it does, the launch failed;
                 * fall through and keep the browser up rather than
                 * hanging (plan section 11's fallback philosophy). M13:
                 * this used to be entirely silent - pressing X on a bad
                 * ELF, or one whose device was removed since the boot-
                 * time scan, produced no visible feedback at all,
                 * indistinguishable from the launch attempt itself
                 * hanging. Now shown via the status line for a few
                 * seconds instead. */
                logMsg("launch failed: %s", entries[focus].path);
                launchFailedFramesLeft = 180;
            }
        }

        /* The routine per-frame clear stops at safeBottom now, leaving
         * the status-line strip below it untouched except on the few
         * frames right after its text actually changes (below) - part of
         * the same diagnostic: a region that's touched every frame vs.
         * one that's only touched on real change. */
        if (theme->hasBackground) {
            /* Stretched to fill the whole screen via UV mapping - the
             * background's own baked pixel size doesn't need to match
             * gsGlobal's runtime-detected resolution (theme/theme.c).
             * Textured draws need the M7-confirmed blend-equation setup
             * (PrimAlphaEnable alone isn't enough), same as bitmap_font.c.
             * v1 is scaled to match the shortened destination height so
             * the image doesn't stretch differently than intended - moot
             * today since no bundled theme actually has a background. */
            gsKit_set_primalpha(gsGlobal, GS_SETREG_ALPHA(0, 1, 0, 1, 0), 0);
            gsKit_set_test(gsGlobal, GS_ATEST_OFF);
            gsKit_set_test(gsGlobal, GS_ZTEST_OFF);
            /* Neutral modulation: RGB 0xFF (matches bitmap_font.c's pure-
             * white glyph pixels needing 0xFF to render untinted) and
             * alpha 0x80, the GS's own 7-bit "fully opaque" value - not
             * 0x80,0x80,0x80, which would multiplicatively halve the
             * background's brightness. */
            gsKit_prim_sprite_texture(gsGlobal, &theme->background, 0.0f, 0.0f, 0.0f, 0.0f, (float)gsGlobal->Width,
                                       safeBottom, (float)theme->background.Width,
                                       (float)theme->background.Height * (safeBottom / (float)gsGlobal->Height), 0,
                                       GS_SETREG_RGBAQ(0xFF, 0xFF, 0xFF, 0x80, 0x00));
            gsKit_set_test(gsGlobal, GS_ZTEST_ON);
            gsKit_set_test(gsGlobal, GS_ATEST_ON);
            gsKit_set_primalpha(gsGlobal, GS_BLEND_BACK2FRONT, 0);
        } else {
            /* Every theme color here (bg/tile/focus) uses alpha=0x00 -
             * never meant as "transparent", just "unused" on a flat-
             * shaded, non-textured primitive. Disabling blending (below)
             * wasn't enough on its own: alpha TESTING is a separate,
             * earlier pipeline stage, and bitmapFontPrint() leaves
             * GS_ATEST_ON as its "resting" state after every text draw.
             * If that mode is configured to reject alpha=0 fragments
             * (common for punch-through masking), every pixel of this
             * fill gets discarded before blending is ever considered -
             * explaining why disabling PrimAlphaEnable alone didn't fix
             * the earlier ghosting. Disabling the alpha test too
             * guarantees this fill actually writes. */
            gsGlobal->PrimAlphaEnable = GS_SETTING_OFF;
            gsKit_set_test(gsGlobal, GS_ATEST_OFF);
            gsKit_set_test(gsGlobal, GS_ZTEST_OFF);
            gsKit_prim_sprite(gsGlobal, 0.0f, 0.0f, (float)gsGlobal->Width, safeBottom, 0, theme->bgColor);
            gsKit_set_test(gsGlobal, GS_ZTEST_ON);
            gsKit_set_test(gsGlobal, GS_ATEST_ON);
            gsGlobal->PrimAlphaEnable = GS_SETTING_ON;
        }

        for (i = 0; i < entryCount; i++) {
            int col = i % GRID_COLS;
            int row = i / GRID_COLS;
            float x = marginX + col * (cellSize + gap);
            float y = marginY + row * (cellSize + gap);

            if (y + cellSize > safeBottom)
                break; /* no scrolling yet - a later milestone's problem */

            /* Same defensive opaque-fill guard as the background clear
             * above - both blending AND alpha testing disabled, since a
             * flat-shaded alpha=0x00 fill shouldn't be exposed to
             * whatever state the last text draw left either stage in. */
            gsGlobal->PrimAlphaEnable = GS_SETTING_OFF;
            gsKit_set_test(gsGlobal, GS_ATEST_OFF);
            gsKit_set_test(gsGlobal, GS_ZTEST_OFF);
            gsKit_prim_sprite(gsGlobal, x, y, x + cellSize, y + cellSize, 1,
                               i == focus ? theme->focusColor : theme->tileColor);
            gsKit_set_test(gsGlobal, GS_ZTEST_ON);
            gsKit_set_test(gsGlobal, GS_ATEST_ON);
            gsGlobal->PrimAlphaEnable = GS_SETTING_ON;

            /* Build the full "[*]name (count)" string first, then
             * truncate to whatever fits the tile - a favorited, heavily-
             * launched entry should lose its count/name tail before it
             * loses the favorite marker, which is why the marker is
             * prepended rather than appended. */
            char full[80];
            int fi = 0;
            if (metas[i].favorite)
                full[fi++] = '*';
            const char *name = baseName(entries[i].path);
            while (*name && fi < 60)
                full[fi++] = *name++;
            if (metas[i].launchCount > 0 && fi < 70)
                fi += sprintf(full + fi, " (%d)", metas[i].launchCount);
            full[fi] = '\0';

            char label[64];
            int len = 0;
            while (full[len] && len < maxLabelChars)
                len++;
            memcpy(label, full, len);
            label[len] = '\0';

            if (fontOk)
                bitmapFontPrint(gsGlobal, &font, x + 4.0f, y + cellSize - 20.0f, theme->labelColor, label);
        }

        /* Explicit strip clear, since the routine full-screen fill above
         * stops at safeBottom and never touches this area - cleared here
         * instead, right before (re)drawing the text, using the same
         * guaranteed-opaque guards. Done unconditionally every frame,
         * same as the background/tiles above: gsGlobal double-buffers via
         * gsKit_sync_flip(), so a region only touched on *some* frames
         * (as this used to be, redrawing only for a few frames right
         * after the text changed) can leave stale text baked into
         * whichever buffer didn't get the update in time - surfacing as
         * old/new text clashing on flip. Redrawing every frame removes
         * that failure mode entirely; the RTC/disc-status RPC itself is
         * still only polled once a second via statusFrameCounter above,
         * so this doesn't add any extra IOP round-trips. */
        gsGlobal->PrimAlphaEnable = GS_SETTING_OFF;
        gsKit_set_test(gsGlobal, GS_ATEST_OFF);
        gsKit_set_test(gsGlobal, GS_ZTEST_OFF);
        gsKit_prim_sprite(gsGlobal, 0.0f, safeBottom, (float)gsGlobal->Width, (float)gsGlobal->Height, 0,
                           theme->bgColor);
        gsKit_set_test(gsGlobal, GS_ZTEST_ON);
        gsKit_set_test(gsGlobal, GS_ATEST_ON);
        gsGlobal->PrimAlphaEnable = GS_SETTING_ON;

        /* Priority: disconnected controller > a recent launch failure >
         * the normal disc/RTC readout. Both overrides count down/reset
         * on their own regardless of whether text actually gets drawn
         * this frame, so they behave correctly even if fontOk is false. */
        const char *lineToShow = statusLine;
        if (disconnectFrames > 30) {
            strcpy(overrideMsg, "controller disconnected");
            lineToShow = overrideMsg;
        } else if (launchFailedFramesLeft > 0) {
            strcpy(overrideMsg, "launch failed");
            lineToShow = overrideMsg;
            launchFailedFramesLeft--;
        }

        if (fontOk)
            bitmapFontPrint(gsGlobal, &font, marginX, safeBottom + 2.0f, theme->labelColor, lineToShow);

        /* M13 debug overlay (toggled with START) - a plain, opaque dark
         * panel over the whole safe area, showing the most recent log
         * lines newest-at-bottom. Deliberately opaque rather than
         * translucent - alpha blending has been the single most
         * troublesome GS state in this whole project (M7's blend
         * equation, M11's Z-test discovery); a solid panel is simplest
         * and needs none of that. */
        if (overlayVisible) {
            gsGlobal->PrimAlphaEnable = GS_SETTING_OFF;
            gsKit_set_test(gsGlobal, GS_ATEST_OFF);
            gsKit_set_test(gsGlobal, GS_ZTEST_OFF);
            gsKit_prim_sprite(gsGlobal, marginX, marginY, marginX + safeW, safeBottom, 1,
                               GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x00, 0x00));
            gsKit_set_test(gsGlobal, GS_ZTEST_ON);
            gsKit_set_test(gsGlobal, GS_ATEST_ON);
            gsGlobal->PrimAlphaEnable = GS_SETTING_ON;

            if (fontOk) {
                char header[48];
                sprintf(header, "[SQUARE] disk logging: %s", debugLoggingOn ? "ON" : "OFF");
                bitmapFontPrint(gsGlobal, &font, marginX + 4.0f, marginY + 4.0f,
                                GS_SETREG_RGBAQ(0xFF, 0xE0, 0x80, 0x80, 0x00), header);

                int n = logLineCount();
                int maxRows = (int)((safeBottom - marginY) / 16.0f) - 2;
                int startIdx = (n > maxRows) ? n - maxRows : 0;
                int row = 0;
                while (startIdx + row < n) {
                    const char *line = logLine(startIdx + row);
                    if (line)
                        bitmapFontPrint(gsGlobal, &font, marginX + 4.0f, marginY + 4.0f + (row + 1) * 16.0f,
                                         GS_SETREG_RGBAQ(0xFF, 0xFF, 0xFF, 0x80, 0x00), line);
                    row++;
                }
            }
        }

        gsKit_queue_exec(gsGlobal);
        gsKit_sync_flip(gsGlobal);
    }

    return 0;
}
